## Data Encoding
##### Data encoding is the process of converting categorical or text data into numerical form so that machine learning algorithms can understand and process it. Since most models work only with numbers, encoding helps transform values like names, categories, or labels into meaningful numeric representations without changing their underlying information. Common encoding methods include label encoding, where each category is assigned a unique number, and one-hot encoding, where categories are represented using binary vectors. Data encoding is an essential step in data preprocessing because it makes raw, non-numeric data usable for training accurate machine learning models.

##### 1. Label Encoding and Ordinal Encoding
##### 2. Nominal or One-Hot Encoding
##### 3. Target Guided Ordinal Encoding

In [21]:
# Difference between ordinal and label encoding

### Label Encoding: assigns numbers to categories without any ranking.
#### Example: Red=0, Blue=1, Green=2

### Ordinal Encoding: assigns numbers based on proper order/rank.
#### Example: Small=1, Medium=2, Large=3

## Nominal/OHE Encoding

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
# Create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [9]:
# Create an instance of Onehotencoder
encoder=OneHotEncoder() # This creates an object (instance) of OneHotEncoder

In [11]:
encoded=encoder.fit_transform(df[['color']]).toarray()

### It converts the color column into One-Hot Encoded numeric values.

###### Breakdown (very short):

###### df[['color']] → selects the color column as a 2D DataFrame

###### fit_transform() → learns unique colors and converts them into 0s and 1s

###### .toarray() → changes the result from sparse format to a normal NumPy array

In [12]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out()) # Converts the encoded NumPy array into a Pandas DataFrame

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [13]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

## Label Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [15]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Gaurish16\OneDrive\Desktop\Udemy\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

## Ordinal Encoding

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [18]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [19]:
# Create an instance of OrdinalEncoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [20]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

## Target Guided Ordinal Encoding

In [22]:
import pandas as pd

In [23]:
df=pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200,150,300,250,180,320]
})

In [24]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [26]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [27]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [28]:
df['city_encoded']=df['city'].map(mean_price)

In [29]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [30]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0