**Pandas** is a powerful Python library used for **data manipulation and data analysis**. It provides easy-to-use data structures like **Series** and **DataFrame**, which allow data to be cleaned, filtered, transformed, and analyzed efficiently. Pandas makes working with structured data such as CSV files, Excel sheets, and databases simple and intuitive. It is widely used in data science, machine learning, and analytics because it helps handle missing data, perform statistical analysis, and visualize trends quickly.

A **Series** in **Pandas** is a **one-dimensional labeled data structure** used to store a sequence of values along with their corresponding labels, called an **index**. It is similar to a column in a table or an enhanced Python list, but with the added benefit of indexing, which makes data access and manipulation easier. A Series can hold different data types such as integers, floats, strings, or even Python objects, and it is commonly used for handling and analyzing single-column data in Pandas.

In [36]:
#Series
import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [37]:
# Create a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
series=pd.Series(data,index=index)
print(series)

a    10
b    20
c    30
dtype: int64

A **DataFrame** in **Pandas** is a **two-dimensional, labeled data structure** used to store and manage data in a **table-like format**, similar to an Excel sheet or a SQL table. It consists of **rows and columns**, where each column can hold different data types, and both rows and columns have labels (index and column names). DataFrames make it easy to organize, filter, analyze, and manipulate large datasets efficiently, which is why they are widely used in data analysis and data science.

In [38]:
# Dataframe
# Create a Dataframe from a dictionary of list

data={
    'Name':['Dev','Rey','John'],
    'Age':[25,30,35],
    'City':['Bangalore','New York','Madrid']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age       City
0   Dev   25  Bangalore
1   Rey   30   New York
2  John   35     Madrid
<class 'pandas.core.frame.DataFrame'>

In [9]:
# Create a dataframe from a list of dictionaries

data=[
    {'Name':'Jai','Age':26,'City':'Delhi'},
    {'Name':'Dev','Age':28,'City':'Manali'},
    {'Name':'Tej','Age':25,'City':'Jaipur'},
    {'Name':'Jack','Age':29,'City':'Daman'},
]
df=pd.DataFrame(data)
print(df)

   Name  Age    City
0   Jai   26   Delhi
1   Dev   28  Manali
2   Tej   25  Jaipur
3  Jack   29   Daman

In [50]:
# With CSV file
df=pd.read_csv('transportation_practice.csv')
df.head(5)

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count
0,T001,07-01-2025,Metro,Delhi-Ghaziabad,107,57,666,20
1,T002,22-01-2025,Metro,Delhi-Ghaziabad,82,188,575,88
2,T003,09-01-2025,Bus,Airport-Delhi,207,135,996,80
3,T004,03-01-2025,Taxi,Delhi-Faridabad,8,210,777,34
4,T005,05-01-2025,Bus,Delhi-Faridabad,15,194,900,291

In [40]:
df.tail(5)

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count
5,T006,21-01-2025,Train,Dwarka-Noida,268,148,1195,278
6,T007,20-01-2025,Bus,Noida-Delhi,137,110,973,298
7,T008,11-01-2025,Bus,Noida-Gurgaon,20,76,817,224
8,T009,15-01-2025,Train,Airport-Delhi,167,97,1007,148
9,T010,29-01-2025,Metro,Delhi-Ghaziabad,220,202,1013,35

In [41]:
# Accessing the data
df['Route']

0    Delhi-Ghaziabad
1    Delhi-Ghaziabad
2      Airport-Delhi
3    Delhi-Faridabad
4    Delhi-Faridabad
5       Dwarka-Noida
6        Noida-Delhi
7      Noida-Gurgaon
8      Airport-Delhi
9    Delhi-Ghaziabad
Name: Route, dtype: object

The difference between `loc` and `iloc` in Pandas lies in how they access data. The `loc` method is **label-based**, meaning it selects rows and columns using their names or labels and includes the ending index in slicing. It also supports boolean conditions for filtering data. In contrast, `iloc` is **integer position–based**, meaning it selects data using numerical positions starting from zero, excludes the ending index in slicing, and does not use row or column labels.

In [42]:
df.loc[0]

Trip_ID                       T001
Date                    07-01-2025
Transport_Type               Metro
Route              Delhi-Ghaziabad
Distance_km                    107
Duration_min                    57
Fare_INR                       666
Passenger_Count                 20
Name: 0, dtype: object

In [23]:
df.iloc[0]

Trip_ID                       T001
Date                    07-01-2025
Transport_Type               Metro
Route              Delhi-Ghaziabad
Distance_km                    107
Duration_min                    57
Fare_INR                       666
Passenger_Count                 20
Name: 0, dtype: object

In [43]:
# Accessing a specific element
df.at[1,'Transport_Type']

'Metro'

In [44]:
# Accessing a specified element using iat
df.iat[2,2]

'Bus'

In [45]:
# Adding a column
df['Age']=[20,21,24,23,34,56,45,32,27,29]
df

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count,Age
0,T001,07-01-2025,Metro,Delhi-Ghaziabad,107,57,666,20,20
1,T002,22-01-2025,Metro,Delhi-Ghaziabad,82,188,575,88,21
2,T003,09-01-2025,Bus,Airport-Delhi,207,135,996,80,24
3,T004,03-01-2025,Taxi,Delhi-Faridabad,8,210,777,34,23
4,T005,05-01-2025,Bus,Delhi-Faridabad,15,194,900,291,34
5,T006,21-01-2025,Train,Dwarka-Noida,268,148,1195,278,56
6,T007,20-01-2025,Bus,Noida-Delhi,137,110,973,298,45
7,T008,11-01-2025,Bus,Noida-Gurgaon,20,76,817,224,32
8,T009,15-01-2025,Train,Airport-Delhi,167,97,1007,148,27
9,T010,29-01-2025,Metro,Delhi-Ghaziabad,220,202,1013,35,29

In [46]:
# Remove a column
df.drop('Age',axis=1,inplace=True) #axis helps to access through column but it doesn't save permanently so inplace is used to save the  hanges permanently
df

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count
0,T001,07-01-2025,Metro,Delhi-Ghaziabad,107,57,666,20
1,T002,22-01-2025,Metro,Delhi-Ghaziabad,82,188,575,88
2,T003,09-01-2025,Bus,Airport-Delhi,207,135,996,80
3,T004,03-01-2025,Taxi,Delhi-Faridabad,8,210,777,34
4,T005,05-01-2025,Bus,Delhi-Faridabad,15,194,900,291
5,T006,21-01-2025,Train,Dwarka-Noida,268,148,1195,278
6,T007,20-01-2025,Bus,Noida-Delhi,137,110,973,298
7,T008,11-01-2025,Bus,Noida-Gurgaon,20,76,817,224
8,T009,15-01-2025,Train,Airport-Delhi,167,97,1007,148
9,T010,29-01-2025,Metro,Delhi-Ghaziabad,220,202,1013,35

In [47]:
# Add fare to the column
df['Fare_INR']=df['Fare_INR']+10
df

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count
0,T001,07-01-2025,Metro,Delhi-Ghaziabad,107,57,676,20
1,T002,22-01-2025,Metro,Delhi-Ghaziabad,82,188,585,88
2,T003,09-01-2025,Bus,Airport-Delhi,207,135,1006,80
3,T004,03-01-2025,Taxi,Delhi-Faridabad,8,210,787,34
4,T005,05-01-2025,Bus,Delhi-Faridabad,15,194,910,291
5,T006,21-01-2025,Train,Dwarka-Noida,268,148,1205,278
6,T007,20-01-2025,Bus,Noida-Delhi,137,110,983,298
7,T008,11-01-2025,Bus,Noida-Gurgaon,20,76,827,224
8,T009,15-01-2025,Train,Airport-Delhi,167,97,1017,148
9,T010,29-01-2025,Metro,Delhi-Ghaziabad,220,202,1023,35

In [51]:
df.drop(0,inplace=True)
df

,Trip_ID,Date,Transport_Type,Route,Distance_km,Duration_min,Fare_INR,Passenger_Count
1,T002,22-01-2025,Metro,Delhi-Ghaziabad,82,188,575,88
2,T003,09-01-2025,Bus,Airport-Delhi,207,135,996,80
3,T004,03-01-2025,Taxi,Delhi-Faridabad,8,210,777,34
4,T005,05-01-2025,Bus,Delhi-Faridabad,15,194,900,291
5,T006,21-01-2025,Train,Dwarka-Noida,268,148,1195,278
6,T007,20-01-2025,Bus,Noida-Delhi,137,110,973,298
7,T008,11-01-2025,Bus,Noida-Gurgaon,20,76,817,224
8,T009,15-01-2025,Train,Airport-Delhi,167,97,1007,148
9,T010,29-01-2025,Metro,Delhi-Ghaziabad,220,202,1013,35

In [52]:
# Describe the Dataframe
print("Statistical Summary:\n",df.describe())

Statistical Summary:
        Distance_km  Duration_min     Fare_INR  Passenger_Count
count     9.000000      9.000000     9.000000         9.000000
mean    124.888889    151.111111   917.000000       164.000000
std      97.959742     49.732898   177.069901       110.289392
min       8.000000     76.000000   575.000000        34.000000
25%      20.000000    110.000000   817.000000        80.000000
50%     137.000000    148.000000   973.000000       148.000000
75%     207.000000    194.000000  1007.000000       278.000000
max     268.000000    210.000000  1195.000000       298.000000

*Data manipulation and analysis* with Pandas involves cleaning, organizing, transforming, and examining data efficiently using Pandas’ powerful data structures like Series and DataFrames. With Pandas, you can easily load data from files such as CSV or Excel, handle missing values, filter rows and columns, sort and group data, create new columns, and perform statistical operations. It allows quick insights through functions like aggregation, merging, and reshaping datasets, making it an essential tool for data analysis, data science, and machine learning workflows.

In [63]:
import pandas as pd

df=pd.read_csv('Product_Data_Pandas_Practice.csv')
df

    Product_ID   Product_Name     Category  Price  Quantity_Sold  Rating
0            1         Laptop  Electronics  65000           15.0     NaN
1            2     Smartphone  Electronics  30000           40.0     4.3
2            3         Tablet  Electronics  20000            NaN     4.2
3            4     Headphones  Accessories   2500           60.0     4.1
4            5     Smartwatch    Wearables  15000           20.0     4.4
5            6       Keyboard  Accessories   1200           70.0     4.0
6            7          Mouse  Accessories    800           90.0     3.9
7            8        Monitor  Electronics  18000            NaN     4.3
8            9        Printer  Electronics   9000           18.0     4.0
9           10         Router   Networking   3500           35.0     4.1
10          11         Webcam  Accessories   4000           45.0     4.2
11          12     Microphone  Accessories   5500           28.0     4.3
12          13        Speaker  Accessories   6000           32.0     4.4
13          14     Power Bank  Accessories   2000           50.0     4.1
14          15        Charger  Accessories   1800           55.0     4.0
15          16      USB Cable  Accessories    500          100.0     NaN
16          17     Hard Drive      Storage   5500           22.0     4.2
17          18            SSD      Storage   8500           26.0     4.5
18          19  Graphics Card     Hardware  45000           10.0     4.6
19          20      Processor     Hardware  32000           12.0     4.7

In [56]:
df.head(5)

   Product_ID Product_Name     Category  Price  Quantity_Sold  Rating
0           1       Laptop  Electronics  65000             15     4.5
1           2   Smartphone  Electronics  30000             40     4.3
2           3       Tablet  Electronics  20000             25     4.2
3           4   Headphones  Accessories   2500             60     4.1
4           5   Smartwatch    Wearables  15000             20     4.4

In [57]:
df.tail(5)

    Product_ID   Product_Name     Category  Price  Quantity_Sold  Rating
15          16      USB Cable  Accessories    500            100     3.8
16          17     Hard Drive      Storage   5500             22     4.2
17          18            SSD      Storage   8500             26     4.5
18          19  Graphics Card     Hardware  45000             10     4.6
19          20      Processor     Hardware  32000             12     4.7

In [58]:
df.describe()

       Product_ID        Price  Quantity_Sold     Rating
count    20.00000     20.00000      20.000000  20.000000
mean     10.50000  13790.00000      39.150000   4.230000
std       5.91608  17188.64068      25.138092   0.238636
min       1.00000    500.00000      10.000000   3.800000
25%       5.75000   2375.00000      21.500000   4.075000
50%      10.50000   5750.00000      31.000000   4.200000
75%      15.25000  18500.00000      51.250000   4.400000
max      20.00000  65000.00000     100.000000   4.700000

In [60]:
df.dtypes

Product_ID         int64
Product_Name      object
Category          object
Price              int64
Quantity_Sold      int64
Rating           float64
dtype: object

In [64]:
# Hnadling Misiing values
df.isnull().any()

Product_ID       False
Product_Name     False
Category         False
Price            False
Quantity_Sold     True
Rating            True
dtype: bool

In [65]:
df.isnull().sum()

Product_ID       0
Product_Name     0
Category         0
Price            0
Quantity_Sold    2
Rating           2
dtype: int64

In [69]:
# Filling missing values with the mean of the column
df['Rating_fill']=df['Rating'].fillna(df['Rating'].mean())
df

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Rating,Rating_fill
0,1,Laptop,Electronics,65000,15.0,NaN,4.238889
1,2,Smartphone,Electronics,30000,40.0,4.3,4.300000
2,3,Tablet,Electronics,20000,NaN,4.2,4.200000
3,4,Headphones,Accessories,2500,60.0,4.1,4.100000
4,5,Smartwatch,Wearables,15000,20.0,4.4,4.400000
5,6,Keyboard,Accessories,1200,70.0,4.0,4.000000
6,7,Mouse,Accessories,800,90.0,3.9,3.900000
7,8,Monitor,Electronics,18000,NaN,4.3,4.300000
8,9,Printer,Electronics,9000,18.0,4.0,4.000000
9,10,Router,Networking,3500,35.0,4.1,4.100000
10,11,Webcam,Accessories,4000,45.0,4.2,4.200000
11,12,Microphone,Accessories,5500,28.0,4.3,4.300000
12,13,Speaker,Accessories,6000,32.0,4.4,4.400000
13,14,Power Bank,Accessories,2000,50.0,4.1,4.100000
14,15,Charger,Accessories,1800,55.0,4.0,4.000000
15,16,USB Cable,Accessories,500,100.0,NaN,4.238889
16,17,Hard Drive,Storage,5500,22.0,4.2,4.200000
17,18,SSD,Storage,8500,26.0,4.5,4.500000
18,19,Graphics Card,Hardware,45000,10.0,4.6,4.600000
19,20,Processor,Hardware,32000,12.0,4.7,4.700000

In [70]:
df.dtypes

Product_ID         int64
Product_Name      object
Category          object
Price              int64
Quantity_Sold    float64
Rating           float64
Rating_fill      float64
dtype: object

In [71]:
# Renaming Columns  
df=df.rename(columns={'Product_ID':'PID'})
df

    PID   Product_Name     Category  Price  Quantity_Sold  Rating  Rating_fill
0     1         Laptop  Electronics  65000           15.0     NaN     4.238889
1     2     Smartphone  Electronics  30000           40.0     4.3     4.300000
2     3         Tablet  Electronics  20000            NaN     4.2     4.200000
3     4     Headphones  Accessories   2500           60.0     4.1     4.100000
4     5     Smartwatch    Wearables  15000           20.0     4.4     4.400000
5     6       Keyboard  Accessories   1200           70.0     4.0     4.000000
6     7          Mouse  Accessories    800           90.0     3.9     3.900000
7     8        Monitor  Electronics  18000            NaN     4.3     4.300000
8     9        Printer  Electronics   9000           18.0     4.0     4.000000
9    10         Router   Networking   3500           35.0     4.1     4.100000
10   11         Webcam  Accessories   4000           45.0     4.2     4.200000
11   12     Microphone  Accessories   5500           28.0     4.3     4.300000
12   13        Speaker  Accessories   6000           32.0     4.4     4.400000
13   14     Power Bank  Accessories   2000           50.0     4.1     4.100000
14   15        Charger  Accessories   1800           55.0     4.0     4.000000
15   16      USB Cable  Accessories    500          100.0     NaN     4.238889
16   17     Hard Drive      Storage   5500           22.0     4.2     4.200000
17   18            SSD      Storage   8500           26.0     4.5     4.500000
18   19  Graphics Card     Hardware  45000           10.0     4.6     4.600000
19   20      Processor     Hardware  32000           12.0     4.7     4.700000

In [73]:
# Change Datatypes
df['QuantitySold_new']=df['Quantity_Sold'].fillna(df['Quantity_Sold'].mean()).astype(int)# fillna is done as it has missing values
df

,PID,Product_Name,Category,Price,Quantity_Sold,Rating,Rating_fill,QuantitySold_new
0,1,Laptop,Electronics,65000,15.0,NaN,4.238889,15
1,2,Smartphone,Electronics,30000,40.0,4.3,4.300000,40
2,3,Tablet,Electronics,20000,NaN,4.2,4.200000,40
3,4,Headphones,Accessories,2500,60.0,4.1,4.100000,60
4,5,Smartwatch,Wearables,15000,20.0,4.4,4.400000,20
5,6,Keyboard,Accessories,1200,70.0,4.0,4.000000,70
6,7,Mouse,Accessories,800,90.0,3.9,3.900000,90
7,8,Monitor,Electronics,18000,NaN,4.3,4.300000,40
8,9,Printer,Electronics,9000,18.0,4.0,4.000000,18
9,10,Router,Networking,3500,35.0,4.1,4.100000,35
10,11,Webcam,Accessories,4000,45.0,4.2,4.200000,45
11,12,Microphone,Accessories,5500,28.0,4.3,4.300000,28
12,13,Speaker,Accessories,6000,32.0,4.4,4.400000,32
13,14,Power Bank,Accessories,2000,50.0,4.1,4.100000,50
14,15,Charger,Accessories,1800,55.0,4.0,4.000000,55
15,16,USB Cable,Accessories,500,100.0,NaN,4.238889,100
16,17,Hard Drive,Storage,5500,22.0,4.2,4.200000,22
17,18,SSD,Storage,8500,26.0,4.5,4.500000,26
18,19,Graphics Card,Hardware,45000,10.0,4.6,4.600000,10
19,20,Processor,Hardware,32000,12.0,4.7,4.700000,12

In [75]:
# Apply Function
df['New_Rating']=df['Rating'].fillna(df['Rating'].mean()).apply(lambda x:x**2)
df

,PID,Product_Name,Category,Price,Quantity_Sold,Rating,Rating_fill,QuantitySold_new,New_Rating
0,1,Laptop,Electronics,65000,15.0,NaN,4.238889,15,17.968179
1,2,Smartphone,Electronics,30000,40.0,4.3,4.300000,40,18.490000
2,3,Tablet,Electronics,20000,NaN,4.2,4.200000,40,17.640000
3,4,Headphones,Accessories,2500,60.0,4.1,4.100000,60,16.810000
4,5,Smartwatch,Wearables,15000,20.0,4.4,4.400000,20,19.360000
5,6,Keyboard,Accessories,1200,70.0,4.0,4.000000,70,16.000000
6,7,Mouse,Accessories,800,90.0,3.9,3.900000,90,15.210000
7,8,Monitor,Electronics,18000,NaN,4.3,4.300000,40,18.490000
8,9,Printer,Electronics,9000,18.0,4.0,4.000000,18,16.000000
9,10,Router,Networking,3500,35.0,4.1,4.100000,35,16.810000
10,11,Webcam,Accessories,4000,45.0,4.2,4.200000,45,17.640000
11,12,Microphone,Accessories,5500,28.0,4.3,4.300000,28,18.490000
12,13,Speaker,Accessories,6000,32.0,4.4,4.400000,32,19.360000
13,14,Power Bank,Accessories,2000,50.0,4.1,4.100000,50,16.810000
14,15,Charger,Accessories,1800,55.0,4.0,4.000000,55,16.000000
15,16,USB Cable,Accessories,500,100.0,NaN,4.238889,100,17.968179
16,17,Hard Drive,Storage,5500,22.0,4.2,4.200000,22,17.640000
17,18,SSD,Storage,8500,26.0,4.5,4.500000,26,20.250000
18,19,Graphics Card,Hardware,45000,10.0,4.6,4.600000,10,21.160000
19,20,Processor,Hardware,32000,12.0,4.7,4.700000,12,22.090000

In [ ]:
# Data Aggregating and Grouping
Grouped_mean=df.groupby('Product_Name')['Price'].mean()
print(Grouped_mean)

Product_Name
Charger           1800.0
Graphics Card    45000.0
Hard Drive        5500.0
Headphones        2500.0
Keyboard          1200.0
Laptop           65000.0
Microphone        5500.0
Monitor          18000.0
Mouse              800.0
Power Bank        2000.0
Printer           9000.0
Processor        32000.0
Router            3500.0
SSD               8500.0
Smartphone       30000.0
Smartwatch       15000.0
Speaker           6000.0
Tablet           20000.0
USB Cable          500.0
Webcam            4000.0
Name: Price, dtype: float64

In [82]:
Grouped_sum=df.groupby(['Category','Product_Name'])['Price'].sum()
print(Grouped_sum)

Category     Product_Name
Accessories  Charger           1800
             Headphones        2500
             Keyboard          1200
             Microphone        5500
             Mouse              800
             Power Bank        2000
             Speaker           6000
             USB Cable          500
             Webcam            4000
Electronics  Laptop           65000
             Monitor          18000
             Printer           9000
             Smartphone       30000
             Tablet           20000
Hardware     Graphics Card    45000
             Processor        32000
Networking   Router            3500
Storage      Hard Drive        5500
             SSD               8500
Wearables    Smartwatch       15000
Name: Price, dtype: int64

In [84]:
# Aggregating Multiple functions
Grouped_agg=df.groupby('Category')['Price'].agg(['mean','sum','count'])
print(Grouped_agg)

                mean     sum  count
Category
Accessories   2700.0   24300      9
Electronics  28400.0  142000      5
Hardware     38500.0   77000      2
Networking    3500.0    3500      1
Storage       7000.0   14000      2
Wearables    15000.0   15000      1

In [85]:
# Merging and Joining Dataframes
# Create Sample Dataframes
df1=pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'],'Value1':[4,5,6]})

In [86]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [87]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [88]:
# Merge Dataframe on the 'Key Columns'
pd.merge(df1,df2,on='Key',how="inner")

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [89]:
# Outer Join
pd.merge(df1,df2,on='Key',how="outer")

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [90]:
# Left Join
pd.merge(df1,df2,on='Key',how="left")

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [91]:
# Right Join
pd.merge(df1,df2,on='Key',how="right")

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6

Reading Data from Different Sources

In [97]:
import pandas as pd
from io import StringIO
Data='{"employee_name":"James","email":"james@email.com","job_profile":[{"title1":"Team Lead"}]}'
df=pd.read_json(StringIO(Data))

In [98]:
df

  employee_name            email              job_profile
0         James  james@email.com  {'title1': 'Team Lead'}

In [99]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@email.com"},"job_profile":{"0":{"title1":"Team Lead"}}}'

In [100]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@email.com","job_profile":{"title1":"Team Lead"}}}'

In [101]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@email.com","job_profile":{"title1":"Team Lead"}}]'

In [104]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")
df.head(5)

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [105]:
df.to_csv("wine.csv")

A **pickle file** is a way for Python to save data so it can be used again later without having to recreate or recompute it. It stores Python objects such as lists, dictionaries, DataFrames, or even machine learning models in a special binary format. The main purpose of a pickle file is to make programs faster and more efficient by allowing you to save the final result of your work and load it back exactly as it was. For example, instead of cleaning a dataset or training a model every time you run your code, you can pickle it once and reload it instantly whenever needed.